### PR TITLE
Create config property "omitFilePathComment"

### PR DESCRIPTION
**Pull request by digocesar**
Some people want to avoid polluting the code with unnecessary comments.

If the name `omitFilePathComment` for this configuration is not good, I welcome suggestions.

### CODE REVIEW

**Comment by absalonv** [comment]
@svenheden this would be a neat feature, e some of us dev use linux and windows which generates  different filepaths

**Comment by digocesar** [comment]
@absalonv You can use my repo version while @svenheden do not accept this PR.
Try `npm install --save digocesar/csharp-models-to-typescript`

**Comment by svenheden** [comment]
Thanks, this is nice!

**Comment by svenheden** [comment]
Released in v0.22.0 just now

**Pull request merged**
