### PR TITLE
Upgrade .NET dependencies (Retarget to .NET 8) and use System.Text.Json

### LINKED ISSUE #73: Dependency vulnerability
The use of component is not working to me.
Visual Studio is saying that Newtonsoft has vulnerabilities.
image

### PR DESCRIPTION
**Pull request by SafeerH**
Upgrade .NET dependencies (Retarget to .NET 8) and replace Newtonsoft.Json with System.Text.Json (also fixes #73)
- .NET Core 3.1 is out of support and causes crash

@svenheden hope you'll like this.

### CODE REVIEW

**Comment by Linkek** [comment]
@svenheden would you mind taking a look at this so csharp-models-to-typescript can be used again?

**Comment by svenheden** [comment]
Sorry guys, I haven't given much attention to this lib lately, that's correct. @digocesar and/or @SafeerH you guys have have made good contributions before, would you like to be added as a maintainers?

**Comment by digocesar** [comment]
Hi @svenheden. Yes, I would. I still use this project and can help maintain it.
I just don't know how the process of publishing a new release to npm is done. But then you do this part... ;)

**Comment by SafeerH** [comment]
Hi @svenheden, same here. I still use this lib and would be happy to help.

**Comment by svenheden** [comment]
Thanks! Have added you both as collaborators to this repo now. Merge whatever you see fit and give me a ping when you want me to publish a new version to npm :)

**Comment by SafeerH** [comment]
Hi @digocesar, would you be able to take a look at this PR? Thanks!

**Comment by digocesar** [comment]
It's not working for me.
I assume it's due to the serializer changing. And I use Windows!
image

Isn't it better to do a PR just to upgrade .Net and components and then doing another PR changing the serializer?

**Comment by SafeerH** [comment]
I'm using Windows too and I don't think it is due to the serializer change. The following section from your screenshot is the output that is generated from the serializer.
image

As per your screenshot, the error is due to a C# compiler warning from a file called `Util.cs`. But there's no such file in this repository and I'm wondering how did you get that file into your codebase (`csharp-models-to-typescript\Util.cs`).

**Comment by digocesar** [comment]
I had this error when I took this new code and put it in the node_modules folder of a project I have and tried to run it. I'll try to analyze the reason for the problem then.

**Comment by digocesar** [comment]
Ok. My mistake testing before. It is working! ;)

**Pull request merged**
